import type { Metadata } from "next";
import "./globals.css";
import SmoothScrolling from "./components/lenis/SmoothScrolling";


import { Cursor } from "./components/cursor/cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Cursor />
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
